// Code generated by hertz generator.

package lmq

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _consumeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _produceMw() []app.HandlerFunc {
	// your code...
	return nil
}
